cnf=prime4294967297.cnf
all:
	./compare-modes.sh $(cnf)
verbose:
	./compare-modes.sh -v $(cnf)
very-verbose:
	./compare-modes.sh -v -v $(cnf)
clean:
	rm -f *.out *.proof *.trimmed
.PHONY: all verbose very-verbose clean
